import React from 'react';
import { ShieldAlert, X, CheckCircle2, HeartHandshake, Scale, Lock } from 'lucide-react';

interface DisclaimerModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({
  isOpen,
  onClose,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 font-sans">
      <div className="bg-[#141418]/85 backdrop-blur-2xl border border-[#2A2A2E]/80 rounded-xl max-w-2xl w-full p-6 text-[#E5E1D8] shadow-[0_8px_32px_rgba(0,0,0,0.5)] relative max-h-[90vh] overflow-y-auto space-y-5">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-[#9E9A90] hover:text-[#F0ECE1] p-1.5 rounded-lg bg-[#1A1A1E] border border-[#2A2A2E] hover:bg-[#2A2A2E] transition cursor-pointer"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="flex items-center space-x-3 pb-4 border-b border-[#2A2A2E]">
          <div className="w-10 h-10 rounded-lg bg-[#C9A050]/20 border border-[#C9A050]/40 flex items-center justify-center text-[#C9A050]">
            <ShieldAlert className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-lg font-serif font-bold text-[#F0ECE1]">Astrological & Ethical Disclaimer</h2>
            <p className="text-xs text-[#9E9A90] mt-0.5">JyotishVeda AI Platform Guidelines & Legal Notices</p>
          </div>
        </div>

        {/* Content */}
        <div className="space-y-4 text-xs text-[#9E9A90] leading-relaxed">
          <div className="p-4 bg-[#1A1A1E] rounded-xl border border-[#2A2A2E] space-y-1.5">
            <div className="flex items-center space-x-2 text-[#C9A050] font-serif font-bold text-xs">
              <Scale className="w-4 h-4 text-[#C9A050]" />
              <span>1. Educational & Spiritual Guidance Purpose</span>
            </div>
            <p className="text-[#E5E1D8]/80">
              Jyotish (Vedic Astrology) and Numerology are ancient Indian philosophical and observational sciences designed to provide guidance, self-reflection, and timing insights. The reports, AI interpretations, and roadmaps generated by this platform are intended strictly for educational, self-development, and cultural preservation purposes.
            </p>
          </div>

          <div className="p-4 bg-[#1A1A1E] rounded-xl border border-[#2A2A2E] space-y-1.5">
            <div className="flex items-center space-x-2 text-[#C9A050] font-serif font-bold text-xs">
              <HeartHandshake className="w-4 h-4 text-[#C9A050]" />
              <span>2. Non-Substitution of Professional Advice</span>
            </div>
            <p className="text-[#E5E1D8]/80">
              Astrological forecasts do NOT constitute medical diagnosis, psychiatric therapy, legal representation, or certified financial/investment advisory. Users should always consult certified medical professionals, licensed financial planners, or legal counsel for critical health, legal, or investment decisions.
            </p>
          </div>

          <div className="p-4 bg-[#1A1A1E] rounded-xl border border-[#2A2A2E] space-y-1.5">
            <div className="flex items-center space-x-2 text-[#C9A050] font-serif font-bold text-xs">
              <Lock className="w-4 h-4 text-[#C9A050]" />
              <span>3. Data Privacy & Karmic Sovereignty</span>
            </div>
            <p className="text-[#E5E1D8]/80">
              All user birth information, questions, and consultation sessions are stored with confidentiality. The platform honors individual Free Will (Purushartha) as paramount—planetary placements represent cosmic weather, but conscious human actions (Karma) shape final destiny.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="pt-2 flex justify-end">
          <button
            onClick={onClose}
            className="px-6 py-2.5 rounded-lg bg-[#C9A050] hover:bg-[#D4AF37] text-[#0D0D0F] font-bold text-xs shadow-md shadow-[#C9A050]/20 cursor-pointer transition flex items-center space-x-1.5"
          >
            <CheckCircle2 className="w-4 h-4" />
            <span>I Understand and Acknowledge</span>
          </button>
        </div>
      </div>
    </div>
  );
};
